export const data = [
  {
    id: 1,
    name: "sunscreen".toUpperCase(),
    image: "/Sunscreen.png",
    price: 1155,
  },
  {
    id: 2,
    name: "facekit",
    image: "/facekit.png",
    price: 1141,
  },
  {
    id: 3,
    name: "facetoner",
    image: "/facetoner.png",
    price: 1178,
  },
  {
    id: 4,
    name: "faceSerum",
    image: "/faceSerum.png",
    price: 1156,
  },
  {
    id: 5,
    name: "faceSerum",
    image: "/faceSerum.png",
    price: 1116,
  },
  {
    id: 6,
    name: "faceSerum",
    image: "/faceSerum.png",
    price: 1111,
  },
  {
    id: 7,
    name: "faceSerum",
    image: "/faceSerum.png",
    price: 2233,
  },
  {
    id: 8,
    name: "faceSerum",
    image: "/faceSerum.png",
    price: 4567,
  },
  {
    id: 9,
    name: "faceSerum",
    image: "/faceSerum.png",
    price: 9000,
  },
  {
    id: 10,
    name: "faceSerum",
    image: "/faceSerum.png",
    price: 2300,
  },
  {
    id: 11,
    name: "faceSerum",
    image: "/faceSerum.png",
    price: 2345,
  },
  {
    id: 12,
    name: "faceSerum",
    image: "/facetoner.png",
    price: 4566,
  },
  {
    id: 13,
    name: "faceSerum",
    image: "/faceSerum.png",
    price: 9899,
  },
  {
    id: 14,
    name: "faceSerum",
    image: "/facetoner.png",
    price: 2344,
  },
  {
    id: 15,
    name: "faceSerum",
    image: "/faceSerum.png",
    price: 1255,
  },
  {
    id: 16,
    name: "faceSerum",
    image: "/faceSerum.png",
    price: 9088,
  },
  {
    id: 17,
    name: "faceSerum",
    image: "/facetoner.png",
    price: 6577,
  },
];
